# Generated by Django 4.0 on 2022-10-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.IntegerField()),
                ('cse', models.IntegerField()),
                ('DBMS', models.IntegerField()),
                ('Web', models.IntegerField()),
                ('Total_marks', models.IntegerField()),
                ('grade', models.CharField(max_length=3)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'db_table': 'marks',
            },
        ),
    ]
