# Generated by Django 4.0 on 2022-10-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='Total_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='grade',
        ),
        migrations.AlterField(
            model_name='marks',
            name='DBMS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Web',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='cse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='maths',
            field=models.IntegerField(default=0),
        ),
    ]
